### ISSUE TITLE
Poster

### ISSUE THREAD

**Issue by syralk** [ThePornDatabase/namer#182]
Do not download the poster of the scene

**Comment by 4c0d3r** [comment]
You can disable this in the config if you want - recommend you try

**Comment by 2IkHLHB** [comment]
I don't know if this is what (s)he means, but when an .nfo files is used and we choose to disable any or all images to download, the nfo still saves the direct links to the images (poster, background, performer, etc) Then Plex / Jellyfin will download and save those images into the metadata folders. Before, the nfo's didn't do that and honestly I preferred that, since in my user case I only wanted to download poster files with movies and not with single episodes.

**Comment by 4c0d3r** [comment]
Too long without follow up closing.
