### ISSUE TITLE
possibly ignore date and try to query with just scene name and site?

### ISSUE THREAD

**Issue by PAHelper2** [ThePornDatabase/namer#5]
I've noticed that i have a number of scenes with incorrect dates.  However, the site and scene name is correct, and easy to search in the web UI via the Scene search box.  Could namer possibly try site+scene name if the initial date lookup doesn't work?  Not sure how the query API works.

**Comment by 4c0d3r** [comment]
Namer does currently attempt this, but it's the porndb's api itself that has problems in some cases.    This is a known issue with theporndb, still worth tracking.

**Comment by PAHelper2** [comment]
Okay, here's a nice example: 
```POVD.19.10.01.Rebel.Lynn.Cleaning.Lady.Creep.XXX.MP4-SDCLiP```

It should be dated 19.10.11, but searching for "cleaning lady creep" in the Scene search web UI finds it.  Actually, it finds it TWICE, which is weird.

**Comment by 4c0d3r** [comment]
So namer intentional choose not to treat a file as a match if it is more than 1 day newer or older than the data in tpdb.   This is to prevent false positives.   If you have the namer log enabled in your config this would likely have the correct match at the top sorted by scene name similarity, but namer errs on the side of safety here.   It's intentional left up to the user update the file name in these cases, and re-run namer if they way mp4 tags.

**Comment by 4c0d3r** [comment]
Hmm if this proves to be enough of a problem for certain sites, I could see giving users a site list to ignore date matches.

**Comment by PAHelper2** [comment]
I was thinking of something more like a scoring model:
* matched site +1
* matched scene name +1
* matched date +1
* matched 1 or more performers, +1 per match

And then you need at least a score of 2.  Something like that.  I know those numbers are not good, but I'm trying to figure out a way where the date could be wrong, but other data you parse is enough to say "ok, the date is wrong, but i'm going to match it to Foo anyways".  

But then you'll probably want to write a semi-permanent log that tracks success + score, so you can always go back and see what's happening.

**Comment by 4c0d3r** [comment]
The log in this case can be written next to the file today --- turn on namer log: https://github.com/ThePornDatabase/namer/blob/main/namer.cfg#L50

Matching the "scene" today is done by comparing the powerset of the performers/scene name (a string for each performer, and one for each performer and every other performer and so on, and/or the scene name.   This is because the "scene name" might not be the scene name, but just performers, etc.   And then using a tool called rapid fuzz to match the actual file's "scene name" to all those possibilities, and if any match more than 90%, they are used.    https://github.com/maxbachmann/RapidFuzz#scorers.   This helps with misspellings, extra words, people getting clever with spellings of certain words, etc.    A lot of thought was already put in to this.    The key is that the match is gated however on the data and site matching (the site can have spaces removed, and be a truncation of the actual site) and the date needs to be with 1 day as stated before.   Those matchings are done after the fact.    I understand it can be frustrating if the scene/site name is an exact match and the date is not and it get's rejected, but that's what the namer.log can help with.

**Comment by 4c0d3r** [comment]
if you read the namer log it'll help make the algorithm used clear.

**Comment by PAHelper2** [comment]
Got it!  I'll enable and look at the namer log.  (I've only been following docker logs -f namer)

And apologies if I'm stating dumb stuff that's already handled much better. I'm just thinking out loud. :)

**Comment by 4c0d3r** [comment]
No worries, just makes it clear I need to describe the matching algo better in the readme.rst.    https://github.com/ThePornDatabase/namer#for-the-curious-how-is-a-match-made.    Feel free to take a stab improving it if you want once you read through a few namer.log files (they're short) - as the author it's hard to gauge if I'm describing it sufficiently.

**Comment by 4c0d3r** [comment]
Supported now:  https://github.com/ThePornDatabase/namer/blob/429bae49c3ee4ee3c9a06d70f93b777bebf0b93f/namer.cfg#L76


You have to add each site which will have dates ignored to this list....
